### ISSUE TITLE
Auto-fill in tjänsteledigt mot ram

### ISSUE THREAD

**Issue by aiqueneldar** [krakan/micronomy#14]
When a week isn't 40 hours, and you press "Deliver" a question should be raised if you want tp pad the workweek with "Tjänsteledigt mot ram" for the missing hours.

System should then spread out "Tjänsteledigt mot ram" to pad all working days with less than 8h to be 8h at least, or until 40 hour is reached.

**Comment by krakan** [comment]
I don't really see the point with a dialog here. So, now it's implemented so that the filler line will always be filled in when data is saved and is even disabled so that the user can't fill it in manually.
