### ISSUE TITLE
Add new row to timereport fails

### ISSUE THREAD

**Issue by aiqueneldar** [krakan/micronomy#20]
Might be covered by #3, but to make sure it isn't overlooked.
**What happens**
When you go to edit and add another line to the time report to report on. After you click update you are met with a blank page and the edit does not save. This might always happen, but only tried it while already having 1 line added by official Android App before hand. No matter light/dark setting for interface (don't know if that could do any difference, but tried both)

**Steps to reproduce**
After logging in, klick "Redigera rader" in main UI. -> On edit page add a new line via "Lägg till favorit" drop down (I try to add "Frånvaro - Init Dev Ops". -> click "Uppdatera".

**Expected result**
You will be taken back to either the edit page or the reporting page. Not be met by blank page. Also the new favorite choosen does not get added to your time report even if you manually reload the time reporting page.
Trying to manually reload the blank page does nothing, at least not in the UI.

**Comment by aiqueneldar** [comment]
I spun up a local conatiner and tried it out. Here are the error logs:
`2020-06-07 21:59:49.241  4e00edc7  add data [2 -> 2] 2
2020-06-07 21:59:49.253  4e00edc7  get concurrency
2020-06-07 21:59:50.836  4e00edc7  get-concurrency (datevar) received 404 - retrying [1/10]
An operation first awaited:
  in block  at /app/lib/Micronomy.pm6 (Micronomy) line 318
  in sub get-concurrency at /app/lib/Micronomy.pm6 (Micronomy) line 315
  in sub add-data at /app/lib/Micronomy.pm6 (Micronomy) line 344
  in sub edit at /app/lib/Micronomy.pm6 (Micronomy) line 475
  in method edit at /app/lib/Micronomy.pm6 (Micronomy) line 488
  in block  at /app/lib/Routes.pm6 (Routes) line 33
  in block  at /app/lib/Routes.pm6 (Routes) line 31
  in block  at /usr/share/perl6/site/sources/9A69BC70F2D8C7BD950C926E19009FF093ED8524 (Cro::HTTP::Router) line 133
  in block  at /usr/share/perl6/site/sources/9A69BC70F2D8C7BD950C926E19009FF093ED8524 (Cro::HTTP::Router) line 129

Died with the exception:
    Server responded with 422 Unknown
      in sub get-concurrency at /app/lib/Micronomy.pm6 (Micronomy) line 336
      in sub add-data at /app/lib/Micronomy.pm6 (Micronomy) line 344
      in sub edit at /app/lib/Micronomy.pm6 (Micronomy) line 475
      in method edit at /app/lib/Micronomy.pm6 (Micronomy) line 488
      in block  at /app/lib/Routes.pm6 (Routes) line 33
      in block  at /app/lib/Routes.pm6 (Routes) line 31
      in block  at /usr/share/perl6/site/sources/9A69BC70F2D8C7BD950C926E19009FF093ED8524 (Cro::HTTP::Router) line 133
      in block  at /usr/share/perl6/site/sources/9A69BC70F2D8C7BD950C926E19009FF093ED8524 (Cro::HTTP::Router) line 129

[ERROR] 500 /edit - 172.17.0.1`

**Comment by krakan** [comment]
A bit embarrassing: I had hard coded my own employee number in the code while developing and forgotten to fix it ... And it's totally reasonable by the server to respond 422 Unknown if you combine a concurrency code with the wrong employee.
Can you test this locally or do we have to wait for Joakim to redeploy?
