### ISSUE TITLE
Week starts on wrong day, giving wrong week

### ISSUE THREAD

**Issue by aiqueneldar** [krakan/micronomy#28]
On mondays, last week will be presented in Micronomy as the date-picker starts the week on a Sunday. As such, on Mondays last week will be presented instead of current week.
For example, today Monday (24/8 2020) it is week 35. But in Micronomy it selects today as Sunday (23/8 2020), thus showing week 34 (last week) when login as well as when you press the "Idag" button.
@Bluebottel I don't know if this is in the front end date picker or if it is in the back end code. But ping you so you are aware.

**Comment by aiqueneldar** [comment]
Tried it again. And now I get the expected result of Monday the 24th. 
Is the system running Micronomy on CEST or at least CET? Feels like a case of the system thinking it still yesterday in it's time zone while it's today in local time zone.

**Comment by krakan** [comment]
Nah, it works as designed - on Monday mornings until noon the previous week is displayed - the logic being that if you log in on a Monday morning you probably want to approve last week.
But pressing the "Idag" button should indeed bring you to today an not "today minus 12 hours". So a fix could be to let the POST request from the button go to the current week but let the GET request after logging in behave as today.

**Comment by krakan** [comment]
That should fix it will check on Monday

**Comment by krakan** [comment]
Yep, now the "Idag" button brings you to current week but logging in or just sending a get request brings you to previous week on Monday mornings. Or actually it brings you to whatever week it was 12 hours ago.
