### ISSUE TITLE
Monthly button not working

### ISSUE THREAD

**Issue by aiqueneldar** [krakan/micronomy#30]
Used Master branch version locally and tried to click "Månadssammanställning". Got a white page and logged following error:
2020-09-25 06:51:03.588  807481a4  get-month 2020-09-24
No such method 'first-date-in-month' for invocant of type 'Date'
  in method get-month at /app/lib/Micronomy.pm6 (Micronomy) line 184
  in block  at /app/lib/Routes.pm6 (Routes) line 40
  in block  at /usr/share/perl6/site/sources/9A69BC70F2D8C7BD950C926E19009FF093ED8524 (Cro::HTTP::Router) line 133
  in block  at /usr/share/perl6/site/sources/9A69BC70F2D8C7BD950C926E19009FF093ED8524 (Cro::HTTP::Router) line 129

[ERROR] 500 /month - \*.\*.\*.\*

**Comment by krakan** [comment]
New version out - this should work now.
