### ISSUE TITLE
Gateway timeout when monthly summary is > 1 year

### ISSUE THREAD

**Issue by emdewe** [krakan/micronomy#44]
504 Gateway Time-out
nginx/1.14.2

**Comment by krakan** [comment]
Hm, yes, this may happen if you try to do a summary over many weeks that has not been previously cached as the API is rather slow and micronomy must do at least one API call per (non-cached) week. The program should probably fail more gracefully in this case - perhaps giving an error message when trying to do more than 53 weeks without caching ...
