### ISSUE TITLE
Forward button leads to empty page

### ISSUE THREAD

**Issue by haniffm** [krakan/micronomy#8]
When on last page, clicking on forward arrow button (to change to next week), leads to empty (big white) page.

I can also see that I get 500 error from server and the following console log:

```
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```

**Comment by krakan** [comment]
"Last page"? Vilken sida är det?

**Comment by krakan** [comment]
Det här hör förmodligen ihop med https://github.com/krakan/micronomy/issues/3 - felhanteringen är bristfällig.

**Comment by haniffm** [comment]
Japp, issue #3 täcker nog den här också.

**Comment by krakan** [comment]
Men vilken sida menade du med "last page"? Menade du innevarande vecka? Det kan förmodligen finnas en sista vecka när nästa vecka inte finns i databasen eller nåt. Vecka 18B 2019 är i alla fall första veckan eftersom det var då vi började använda Maconomy.

**Comment by haniffm** [comment]
Jo jag menade innevarande vecka. Alltså vecka 42 just nu (som för min del är "avlämnad").

**Comment by krakan** [comment]
Hm, OK, då var det nog något tillfälligt fel ... eller får du samma fel fortfarande?

**Comment by haniffm** [comment]
Får samma fel nu. För att förtydliga: vecka 42 kan jag se, men när jag klickar på pilen för att byta till vecka 43 så får jag en tom sida.

**Comment by krakan** [comment]
Hm, intressant. Skulle du kunna köra
```
token=$(curl -Isu hanif.farahmand.mokarremi@b3.se "https://b3iaccess.deltekenterprise.com/containers/v1/b3/api_currentemployee/data;any" -H Maconomy-Authentication:X-Reconnect | sed -n 's/^maconomy-reconnect: //p' | tr -d '\r\n')
curl -sH Authorization:"X-Reconnect $token" -H Content-Type:application/json "https://b3iaccess.deltekenterprise.com/containers/v1/b3/timeregistration/data;any?card.datevar=2019-10-21" > micronomy.json
```
och skicka mig innehållet i micronomy.json?

**Comment by krakan** [comment]
Aha, just det ja. Om man inte ställt in att nästa vecka automatiskt ska få samma rader som föregående så har den inga rader och då kan man ju inte läsa data från dem. Funkar det bättre nu? Fast även om det funkar så finns det ju inga rader att fylla i ...

**Comment by haniffm** [comment]
Japp nu funkar det! :)

**Comment by krakan** [comment]
Toppen! Första buggen löst!
