### ISSUE TITLE
Micronomy does not work on IOS devices

### ISSUE THREAD

**Issue by pos42** [krakan/micronomy#9]
Micronomy doesn't work on latest IOS.

It hangs at loading with both safari and chrome. I have also tried https://micronomy.jonaseel.se/login directly. No success. I can't even see the login page, just a nice 100%  black page :)

**Comment by krakan** [comment]
Something weird is going on with the headers. The error message in the log is "Header table index 67 out of range." which seems to indicate that the numbes of headers change mid-call ...
I've monkey patched the library where this occurs to ignore the extra headers which seems to work somewhat but sometimes leads too error 400 "Bad Request" (https://http.cat/400).
I'll try to debug this further and maybe submit a bug report upstream.

Meanwhile; does it work for you now?

**Comment by pos42** [comment]
It does... :) Nice !

But when logging out, it just shows a white blank screen (Safari on IOS). I would have expected to see the login page again...

**Comment by krakan** [comment]
Well, yes, logging out in IOS browsers apparently leads to a 400 - as mentioned above.

**Comment by krakan** [comment]
Found it! The HTTP::HPACK module doesn't play nice with HTTP 2 on IOS. Disabling it and only accepting HTTP 1.1 seems to work.
